
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Gramatica;

/** CUP generated class containing symbol constants. */
public class Json_sym {
  /* terminals */
  public static final int rKey = 11;
  public static final int coma = 7;
  public static final int tk_Entero = 15;
  public static final int nulo = 2;
  public static final int tk_Racional = 13;
  public static final int menos = 16;
  public static final int rBrack = 9;
  public static final int EOF = 0;
  public static final int falso = 4;
  public static final int verdadero = 3;
  public static final int d_puntos = 12;
  public static final int rParen = 6;
  public static final int lBrack = 8;
  public static final int error = 1;
  public static final int lKey = 10;
  public static final int lParen = 5;
  public static final int tk_Cadena = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "nulo",
  "verdadero",
  "falso",
  "lParen",
  "rParen",
  "coma",
  "lBrack",
  "rBrack",
  "lKey",
  "rKey",
  "d_puntos",
  "tk_Racional",
  "tk_Cadena",
  "tk_Entero",
  "menos"
  };
}

