
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Gramatica;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int atributo_TextColor = 27;
  public static final int tk_Entero = 65;
  public static final int tipo_Bool = 35;
  public static final int op_Th = 8;
  public static final int relacional_Diferente = 38;
  public static final int op_Td = 9;
  public static final int cl_Head = 14;
  public static final int cl_Div = 22;
  public static final int op_Table = 7;
  public static final int cl_Hnumber = 16;
  public static final int tk_Caracter = 61;
  public static final int coma = 57;
  public static final int tipo_Double = 37;
  public static final int igual = 48;
  public static final int tipo_Int = 33;
  public static final int atributo_Color = 26;
  public static final int cl_Table = 18;
  public static final int op_Head = 3;
  public static final int op_Div = 11;
  public static final int logico_Not = 45;
  public static final int logico_And = 43;
  public static final int cl_P = 23;
  public static final int tk_Id = 64;
  public static final int relacional_Menor = 41;
  public static final int cl_Body = 15;
  public static final int atributo_Font = 29;
  public static final int lParen = 54;
  public static final int dividido = 51;
  public static final int op_Hnumber = 5;
  public static final int op_Title = 6;
  public static final int relacional_Mayor = 42;
  public static final int res_Print = 30;
  public static final int cl_Html = 13;
  public static final int op_Body = 4;
  public static final int cl_Title = 17;
  public static final int rParen = 55;
  public static final int menos = 50;
  public static final int EOF = 0;
  public static final int tk_Cadena = 63;
  public static final int op_Html = 2;
  public static final int cl_Br = 25;
  public static final int mas = 49;
  public static final int res_Llave = 31;
  public static final int verdadero = 46;
  public static final int error = 1;
  public static final int cl_Hr = 24;
  public static final int atributo_Align = 28;
  public static final int por = 52;
  public static final int punto = 60;
  public static final int cl_Tr = 21;
  public static final int logico_Or = 44;
  public static final int falso = 47;
  public static final int cl_Th = 19;
  public static final int op_P = 12;
  public static final int relacional_MenorIgual = 39;
  public static final int cl_Td = 20;
  public static final int lBrack = 58;
  public static final int tipo_Char = 36;
  public static final int res_Result = 32;
  public static final int tipo_String = 34;
  public static final int rBrack = 59;
  public static final int relacional_MayorIgual = 40;
  public static final int tk_Numero = 62;
  public static final int modulo = 53;
  public static final int op_Tr = 10;
  public static final int p_coma = 56;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "op_Html",
  "op_Head",
  "op_Body",
  "op_Hnumber",
  "op_Title",
  "op_Table",
  "op_Th",
  "op_Td",
  "op_Tr",
  "op_Div",
  "op_P",
  "cl_Html",
  "cl_Head",
  "cl_Body",
  "cl_Hnumber",
  "cl_Title",
  "cl_Table",
  "cl_Th",
  "cl_Td",
  "cl_Tr",
  "cl_Div",
  "cl_P",
  "cl_Hr",
  "cl_Br",
  "atributo_Color",
  "atributo_TextColor",
  "atributo_Align",
  "atributo_Font",
  "res_Print",
  "res_Llave",
  "res_Result",
  "tipo_Int",
  "tipo_String",
  "tipo_Bool",
  "tipo_Char",
  "tipo_Double",
  "relacional_Diferente",
  "relacional_MenorIgual",
  "relacional_MayorIgual",
  "relacional_Menor",
  "relacional_Mayor",
  "logico_And",
  "logico_Or",
  "logico_Not",
  "verdadero",
  "falso",
  "igual",
  "mas",
  "menos",
  "dividido",
  "por",
  "modulo",
  "lParen",
  "rParen",
  "p_coma",
  "coma",
  "lBrack",
  "rBrack",
  "punto",
  "tk_Caracter",
  "tk_Numero",
  "tk_Cadena",
  "tk_Id",
  "tk_Entero"
  };
}

