
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Gramatica;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int res_Break = 23;
  public static final int tk_Entero = 52;
  public static final int tipo_Bool = 11;
  public static final int relacional_Diferente = 25;
  public static final int d_puntos = 45;
  public static final int sentencia_For = 20;
  public static final int vis_Public = 4;
  public static final int sentencia_Case = 21;
  public static final int tk_Caracter = 48;
  public static final int coma = 41;
  public static final int tipo_Double = 13;
  public static final int igual = 35;
  public static final int tipo_Int = 9;
  public static final int vis_Final = 5;
  public static final int logico_Not = 32;
  public static final int logico_And = 30;
  public static final int tk_Id = 51;
  public static final int sentencia_Do = 18;
  public static final int relacional_Menor = 28;
  public static final int res_Return = 24;
  public static final int lParen = 42;
  public static final int tipo_Void = 14;
  public static final int dividido = 38;
  public static final int vis_Private = 3;
  public static final int relacional_Mayor = 29;
  public static final int lKey = 46;
  public static final int rParen = 43;
  public static final int menos = 37;
  public static final int EOF = 0;
  public static final int res_Import = 6;
  public static final int tk_Cadena = 50;
  public static final int mas = 36;
  public static final int verdadero = 33;
  public static final int error = 1;
  public static final int por = 39;
  public static final int punto = 40;
  public static final int sentencia_Default = 22;
  public static final int sentencia_While = 17;
  public static final int logico_Or = 31;
  public static final int res_New = 8;
  public static final int falso = 34;
  public static final int sentencia_Else = 16;
  public static final int relacional_MenorIgual = 26;
  public static final int sentencia_If = 15;
  public static final int res_Class = 7;
  public static final int tipo_Char = 12;
  public static final int tipo_String = 10;
  public static final int rKey = 47;
  public static final int relacional_MayorIgual = 27;
  public static final int vis_Protected = 2;
  public static final int sentencia_Switch = 19;
  public static final int tk_Numero = 49;
  public static final int p_coma = 44;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "vis_Protected",
  "vis_Private",
  "vis_Public",
  "vis_Final",
  "res_Import",
  "res_Class",
  "res_New",
  "tipo_Int",
  "tipo_String",
  "tipo_Bool",
  "tipo_Char",
  "tipo_Double",
  "tipo_Void",
  "sentencia_If",
  "sentencia_Else",
  "sentencia_While",
  "sentencia_Do",
  "sentencia_Switch",
  "sentencia_For",
  "sentencia_Case",
  "sentencia_Default",
  "res_Break",
  "res_Return",
  "relacional_Diferente",
  "relacional_MenorIgual",
  "relacional_MayorIgual",
  "relacional_Menor",
  "relacional_Mayor",
  "logico_And",
  "logico_Or",
  "logico_Not",
  "verdadero",
  "falso",
  "igual",
  "mas",
  "menos",
  "dividido",
  "por",
  "punto",
  "coma",
  "lParen",
  "rParen",
  "p_coma",
  "d_puntos",
  "lKey",
  "rKey",
  "tk_Caracter",
  "tk_Numero",
  "tk_Cadena",
  "tk_Id",
  "tk_Entero"
  };
}

